### ISSUE TITLE
Add description of character

### ISSUE THREAD

**Issue by scheini10** [scheini10/scheini10.github.io#3]
#### Description
At the moment the user knows which character will be displayed. However, a short description would help the visitor to understand more precisely what the character is all about.

#### Files
If you need help, take a look at the cheat sheet.
https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf

#### Tasks
In this issue, you will not be guided as closely as in the first one. If you are stuck, you can also look into the first issue on the closed issues page. Follow these steps:
- [ ] Create a new branch with the name ``feature2_short_description``
- [ ] Switch to this branch
- [ ] Add a description of your character (~30-50 words) to the index.md file underneath the title. For this, you should write plain text, without any special formatting or GitHub flavoured markdown.
- [ ] Commit your changes and push them.
- [ ] Create a pull request. At the end of the pull request, you should reference your issue. For this, you write``fixes: # ``  and then select the issue from the list.
- [ ] If all tests have passed, you can merge your changes into the master branch. If the tests fail, look at the comments of the pull request to find out what the problem was. Fix the errors so that the tests pass. A good idea is to repeat the steps of the issue again and see if everything is written correctly. You can also look at the Index.md file on Github and check the correct formatting. If you tried it for 15 minutes without success, you can have a look in the course forum.
- [ ] Delete your feature branch (online and locally). Since you have referenced (by using ``fixes: # ``) the issue in the pull request, you don't have to close it anymore! Switch to the Master Branch and update your local repository (`git pull`).
- [ ] Take a look at your website and see if something has changed. You may have to update the page a few times.

If you have any questions, you can take a look at the course forum.
