### ISSUE TITLE
Add Character traits

### ISSUE THREAD

**Issue by scheini10** [scheini10/scheini10.github.io#5]
#### Description
Each Character has its character traits. Visitors should be able to quickly recognize what makes your character special. Create a subheader of the size H2 and describe your Character with 3-10 keywords below (e.g. loves chocolate cookies)

#### Files
If you need help, take a look at the cheat sheet. We want to use an unordered list and a subheader of size H2.
https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf

#### Tasks
Perform the following steps:
- [ ] Create a new branch named ``feature3_character_traits``
- [ ] Check out this branch
- [ ] Add a subheader (H2) to the index.md file. You have to define the content yourself.
- [ ] Add an unordered list with 3-10 character traits below
- [ ] Commit your changes and push them.
- [ ] Create a pull request. Reference the issue in it.
- [ ] If both tests have passed, you can merge your changes into the master branch. If the tests fail, look at the comments of the pull request to find out what the problem was. Fix the errors so that the tests pass. A good idea is to repeat the steps of the issue and see if everything is written correctly. You can also look at the Index.md file on GitHub and check the correct formatting. If you tried it for 15 minutes without success, you can have a look in the course forum.
- [ ] Delete your feature branch. Switch to the master branch and update your local repository.
- [ ] Take a look at your website and see if something has changed. You may have to update the page a few times.

If you have any questions, you can take a look at the course forum.
