### ISSUE TITLE
Add character quote

### ISSUE THREAD

**Issue by scheini10** [scheini10/scheini10.github.io#6]
#### Description
Not only the characteristics of a character are important, but also the words they've said. To show how special your character is, you should add your favourite quote from your character.

#### Files
If you need help, take a look at the cheat sheet. We would like you to use a **blockquote**.
https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf

#### Tasks
Perform the following steps:
- [ ] Create a new branch named ``feature4_quote``
- [ ] Check out this branch
- [ ] Insert a quote from your character at the bottom of the page. Look into the cheat sheet if necessary
- [ ] Commit your changes and push them.
- [ ] Create a pull request.
- [ ] If both tests have passed, you can merge your changes into the master branch. If the tests fail, look at the comments of the pull request to find out what the problem was. Fix the errors so that the tests pass. A good idea is to repeat the steps of the issue again and see if everything is written correctly. You can also look at the Index.md file on GitHub and check the correct formatting. If you tried it for 15 minutes without success, you can have a look in the course forum.
- [ ] Delete your feature branch. Switch to the master branch and update your local repository.
- [ ] Take a look at your website and see if something has changed. You may have to update the page a few times.

If you have any questions, you can take a look at the course forum.
