### ISSUE TITLE
Add character image

### ISSUE THREAD

**Issue by scheini10** [scheini10/scheini10.github.io#7]
#### Description
The visitors of your site already have a good impression of your character. It is even better to show your character visually. Therefore you should add a picture of your character. For that, you should choose a picture from the internet.

#### Tasks
Carry out the following steps:
- [ ] Create a new branch named ``feature5_image``
- [ ] Check out this branch
- [ ] Search on the search engine of your choice for a picture of your character that you particularly like. Make sure that the image license allows you to use it in private context. Now you need to get the direct link to this image. Get it by clicking on "Show file" or by right-clicking on the picture, "show graphic" and then copying the address from the address bar of your browser.
- [ ] Paste the image at the bottom of your website using the HTML expression ``<img src="URL"/>``. Replace the URL with the link to your image. The cheat sheets also shows a way to display images, but we want you to use this HTML expression.
- [ ] Commit your changes and push them.
- [ ] Create a pull request.
- [ ] If both tests have passed, you can merge your changes into the master branch. If the tests fail, look at the comments of the pull request to find out what the problem was. Fix the errors so that the tests pass. A good idea is to repeat the steps of the issue again and see if everything is written correctly. You can also look at the Index.md file on GitHub and check the correct formatting. If you tried it for 15 minutes without success, you can have a look in the course forum.
- [ ] Delete your feature branch. Switch to the master branch and update your local repository.
- [ ] Take a look at your website and see if something has changed. You may have to update the page a few times.

If you have any questions, you can take a look at the course forum.
